config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :posts do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  resources :rooms, only: [:create, :show] 
  resources :messages, only: :create
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_one_attached :image

  with_options presence: true do
    validates :nickname, length: { maximum: 12 }
    validates :team
    validates :position
  end

  with_options format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: "半角英数字にしてください", on: :create } do
    validates :password
    validates :password_confirmation
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :image, :team, :position, :career])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # ユーザー情報更新後のパス
  def after_update_path_for(resource)
    user_path(current_user)
  end
  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @posts = @user.posts

    # ダイレクトメッセージの記述
      @currentRoomUser = RoomUser.where(user_id: current_user.id) #current_userがすでにルームに参加しているか判断
      @receiveUser = RoomUser.where(user_id: @user.id) #@userがルームに参加しているか判断
      unless @user.id == current_user.id  #current_userとユーザーが同一人物でなければ
        @currentRoomUser.each do |cu| #current_userが参加している全てのルームidを出力
         @receiveUser.each do |u| #@userが参加している全てのルームidを出力
            if cu.room_id == u.room_id #current_userのルームidと@userのルームidで一致するものがあるのか判断
              @haveRoom = true #既にルームがあるよという意味
              @roomId = cu.room_id #current_userが参加しているルームidを変数に代入
            end
          end
        end
        unless @haveRoom #ルームがなかったら
          @room = Room.new
          @RoomUser = RoomUser.new
        end
      end
    # //ダイレクトメッセージの記述
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render 'shared/header' %>

<div class="user-show-info">
  <%# ユーザー情報の詳細 %>
  <div class="user-show-data">
    <p class="user-show-title"><%= @nickname %>さんの情報</p>
    <table class="user-show-table">
      <tbody>
        <tr>
          <th class="user-show-header">名前</th>
          <td class="user-show-calumn"><%= @user.nickname %></td>
        </tr>
        <tr>
          <th class="user-show-header">所属</th>
          <td class="user-show-calumn"><%= @user.team %></td>
        </tr>
        <tr>
          <th class="user-show-header">経歴</th>
          <td class="user-show-calumn"><%= @user.career %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <%#//ユーザー情報の詳細 %>

  <div class="edit-user-btn">
    <% if user_signed_in? && current_user.id == @user.id  %>
      <%= link_to "編集する", edit_user_registration_path %>
    <% end %>
  </div>
  

  <%# メッセージルームに遷移するボタン %>
  <div class="show-chat-btn">
    <% unless @user.id == current_user.id %>
      <% if @haveRoom == true %>
        <%= link_to "メッセージを送る", room_path(@roomId) ,class: "chat-btn"%>
      <% else %>
        <%= form_with model: @room, local: true do |f|%>
          <%= fields_for @RoomUser do |r| %>
            <%= r.hidden_field :user_id, value: @user.id %>
          <% end %>
          <%= f.submit "チャットを始める", class: "chat-btn" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <%#//メッセージルームに遷移するボタン %>

  <%# ログインユーザーの投稿一覧 %>
  <div class="show-contents">
    <h2 class="show-contents-title"><%= @nickname %>さんの投稿</h2>
    <%# 投稿一覧ページのcssを使用
        posts/index.css %>
    <ul class="post-lists">
      <% @posts.each do |post| %>
        <li class="list">
          <%= link_to post_path(post.id) do %>
            <div class="youtube_url">
              <iframe class="video" src="https://www.youtube.com/embed/<%= post.youtube_url.last(11)%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="post-title">
              <%= post.title %>
            </div>
          <% end %>
          <div class="post-date">
            <%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
          </div>
          <div class="post-user">
            <% if post.user.image.attached? %>
              <%= image_tag post.user.image.variant(resize: '150x150'), class: 'user-image'  %>
            <% else %>
              <%= image_tag("user-image.png", class:"user-noicon") %>
            <% end %>
            <%=link_to post.user.nickname, user_path(post.user.id) %>
          </div>
        </li>
      <% end %>
    </ul>
    <%# //投稿一覧ページのcssを使用
        posts/index.css %>
  </div>
  <%# //ログインユーザーの投稿一覧 %>
</div>

<%= render 'shared/footer' %>