config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :posts do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  resources :rooms, only: [:create, :show] 
  resources :messages, only: :create
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title, length: { maximum: 100, message: 'が長すぎます' }
    validates :youtube_url
    validates :text
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :youtube_post, only: :update
  before_action :set_q, only: [:index, :search]

  def index
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # beforeアクションでまとめるとエラーになるため記述
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    # //beforeアクションでまとめるとエラーになるため記述
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    @results = @q.result.includes(:user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :youtube_url, :text).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def youtube_post
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
  end

  def set_q
    @q = Post.ransack(params[:q])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
 <%# cssは新規投稿のものを使用
 app/assets/stylesheets/posts/new.css %>
 
 <%= render "shared/header" %>

<div class="post-main">
  <div class="post-form">
    <%= form_with model: @post,local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>

      <div class="new-post">
        <div class="new-post-title">
          タイトル
        </div>
        <%= f.text_field :title, class:"post-text", id:"post-title", placeholder:"タイトルを入力" %>
        <div class="new-post-title">
          動画URL
        </div>
        <%= f.text_field :youtube_url, class:"post-text", id:"video-url", placeholder:"YouTubeのURLを貼り付けてください" %>
        <div class="new-post-title">
          アピールポイント、説明等
        </div>
        <%= f.text_area :text, class:"post-text", id:"post-explain", placeholder:"テキストを入力" %>
        <div class="new-post-action">
          <%= f.submit "更新する", class:"new-post-btn" %>
        </div>
        <%= link_to "もどる", root_path, class:"new-back-btn" %>
      </div>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <%= search_form_for @q, url: search_posts_path do |f| %>
    <div class="search">
      <%= f.text_field :title_or_text_cont, class: "search-form", placeholder: "キーワード検索" %>
      <%= f.submit "検索", class: "search-btn"%>
    </div>
  <% end %>
  
  <div class="post-contents">
    <h2 class="title">投稿一覧</h2>
    <ul class="post-lists">
      <% @posts.each do |post| %>
        <li class="list">
          <%= link_to post_path(post.id) do %>
            <div class="youtube_url">
              <iframe class="video" src="https://www.youtube.com/embed/<%= post.youtube_url.last(11)%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="post-title">
              <%= post.title %>
            </div>
          <% end %>
          <div class="post-date">
            <%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
          </div>
          <div class="post-user">
            <% if post.user.image.attached? %>
              <%= image_tag post.user.image.variant(resize: '150x150'), class: 'user-image'  %>
            <% else %>
              <%= image_tag("user-image.png", class:"user-noicon") %>
            <% end %>
            <%=link_to post.user.nickname, user_path(post.user.id) %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/new.html.erb
 <%= render "shared/header" %>

<div class="post-main">
  <div class="post-form">
    <h2 class="post-form-title">活躍している姿を発信しよう！</h2>
    <%= form_with model: @post,local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>

      <div class="new-post">
        <div class="new-post-title">
          タイトル
        </div>
        <%= f.text_field :title, class:"post-text", id:"post-title", placeholder:"タイトルを入力" %>
        <div class="new-post-title">
          動画URL
        </div>
        <%= f.text_field :youtube_url, class:"post-text", id:"video-url", placeholder:"YouTubeのURLを貼り付けてください" %>
        <div class="new-post-title">
          アピールポイント、説明等
        </div>
        <%= f.text_area :text, class:"post-text", id:"post-explain", placeholder:"テキストを入力" %>
        <div class="new-post-action">
          <%= f.submit "投稿する", class:"new-post-btn" %>
        </div>
        <%= link_to "もどる", root_path, class:"new-back-btn" %>
      </div>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/search.html.erb
<%= render "shared/header" %>

<div class="search-main">
  <%= search_form_for @q, url: search_posts_path do |f| %>
    <div class="search">
      <%= f.text_field :title_or_text_cont, class: "search-form", placeholder: "キーワード検索" %>
      <%= f.submit "検索", class: "search-btn"%>
    </div>
  <% end %>

  <%# cssは投稿一覧ページのものを使用
 app/assets/stylesheets/posts/index.css %>
  <div class="post-contents">
    <% if @results.length != 0 %>
      <ul class="post-lists">
        <% @results.each do |result| %>
          <li class="list">
            <%= link_to post_path(result.id) do %>
              <div class="youtube_url">
                <iframe class="video" src="https://www.youtube.com/embed/<%= result.youtube_url.last(11)%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              </div>
              <div class="post-title">
                <%= result.title %>
              </div>
            <% end %>
            <div class="post-date">
              <%= result.created_at.strftime("%Y-%m-%d %H:%M") %>
            </div>
            <div class="post-user">
              <% if result.user.image.attached? %>
                <%= image_tag result.user.image.variant(resize: '150x150'), class: "user-image" %>
              <% else %>
                <%= image_tag("user-image.png", class:"user-noicon") %>
              <% end %>
              <%= link_to result.user.nickname, user_path(result.user.id) %>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="search-empty">
        <h1 class="search-empty-title">検索結果がありません</h1>
        <p class="search-empty-message">検索結果がありませんでした。<br>
        入力を間違えていないか確認してください。
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="show-post">

  <%# 投稿の詳細 %>
  <div class="show-area">
    <h2 class="show-post-title">
      <%= @post.title %>
    </h2>
    <div class="show-video-content">
      <iframe class="show-video" src="https://www.youtube.com/embed/<%= @post.youtube_url.last(11)%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="show-post-text">
      <%= @post.text %>
    </div>
    <%# //投稿の詳細 %>

    <%# ユーザー情報の詳細 %>
    <div class="user-data">
      <h2 class="user-title">選手情報</h2>
      <table class="user-table">
        <tbody>
          <tr>
            <th class="user-header">名前</th>
            <td class="user-content"><%= @post.user.nickname %></td>
          </tr>
          <tr>
            <th class="user-header">所属チーム</th>
            <td class="user-content"><%= @post.user.team %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <%# //ユーザー情報の詳細 %>
    
    <div class="action-btn">
    <% if user_signed_in? %>
      <% if current_user.id == @post.user_id %>
        <%= link_to "編集する", edit_post_path(@post.id), class: "edit-btn" %>
        <%= link_to "削除する", post_path(@post.id), method: :delete, class: "delete-btn" %>
      <% end %>
    <% end %>
    </div>
  </div>

</div>

<%= render "shared/footer" %>